### ISSUE TITLE
[BUG] Unable to load the visual in Power bi desktop, getting error "The content is blocked. Contact the site owner to fix the issue."

### ISSUE THREAD

**Issue by manikumarnune123** [dm-p/powerbi-visuals-html-content#102]
I am able to work with Html-Content Visual earlier, recently I am getting below error. Any leads?
![powerbi html content](https://github.com/dm-p/powerbi-visuals-html-content/assets/65438060/a82890fa-4945-4d7d-9dfa-b6b4c3f650b2)

**Comment by dm-p** [comment]
Apologies for missing this. This was an issue introduced by MS that started affecting many custom visuals. I have been working with them for some time now to help resolve it, and it should hopefully have been resolved a while back. If you're still seeing issues, please let me know, and I can ask for more information to pass on to MS.
