### ISSUE TITLE
[ENHANCEMENT] Adjust Cursor Behavior in HTML Visual

### ISSUE THREAD

**Issue by LS-Stud** [dm-p/powerbi-visuals-html-content#107]
Hi Daniel,

Thank you for providing this HTML visual. It's been incredibly useful!

I did notice one small issue: whenever I hover over the visual, the cursor changes from the default arrow to a hand icon. To make it more intuitive, could we have the cursor change only when hovering over clickable links within the visual? I believe this adjustment would greatly enhance the user experience.

I'd really appreciate your help with this improvement.

Many thanks in advance!

Best regards!

**Comment by dm-p** [comment]
Hi, and I'm glad to hear that you find the visual useful! Thanks for creating an issue to help to improve it.

Unfortunately, I just submitted an update a couple of days before your issue was raised, so it might be a while before I can add this as an enhancement.

As a workaround in the meantime, you can override the `cursor` via CSS by creating a measure, e.g.:

```javascript
Cursor Override = "#htmlViewer {
    cursor: auto;
}"
```
You can add this to the [stylesheet](https://www.html-content.com/reference/stylesheet) in the properties pane, and you should have the desired effect.

**Comment by PBI-David** [comment]
Did this get added as a default? I'm still seeing the hand without the custom CSS

**Comment by dm-p** [comment]
No - this hasn't been added as a feature. The CSS is how you'd currently manage it.

**Comment by PBI-David** [comment]
No problem. FYI, when adding this CSS I noticed that also changing  font size using CSS has a weird discrepancy compared to font sizes chosen in the normal format pane. i.e. an 11px in the normal format pane would require approx 15px via CSS to be the same size. Not a big deal but confused me for a while.

**Comment by dm-p** [comment]
Thanks for flagging. Font sizes in the formatting pane are applied as [pt](https://github.com/dm-p/powerbi-visuals-html-content/blob/master/src/domain-utils.ts#L131-L137) and are designed to mirror the way that core visuals are set up. Based on conversion ratios, 11pt works out to somewhere between 14 and 15px, so this makes sense.

It looks like the unit display for that setting in the formatting pane [is a bug](https://github.com/dm-p/powerbi-visuals-html-content/blob/master/src/visual-settings.ts#L158). IIRC, despite being able to set a unit symbol via the formatting pane APIs explicitly, it wasn't being applied in the pane, so I may have left it as-is. Either way, it should show 'pt' there if we can get it to work (and it should now, as Deneb has this correctly applied for the editor font size property.

**Comment by dm-p** [comment]
I've created #128 for the unit sizing issue.

**Comment by PBI-David** [comment]
Thanks Daniel - makes sense.
