### ISSUE TITLE
Script within lite HTML visual WITHOUT external references is not executed[BUG]

### ISSUE THREAD

**Issue by Simon-Sieber1** [dm-p/powerbi-visuals-html-content#108]
**Describe the bug**
Firstly, thanks for the great tool!

I have a simple script to order a HTML table based off a specific column. The script **does not** reference any externally referenced JavaScript. When executing the HTML and JavaScript in the regular version it works. However, the lite version refuses to execute the script. Unfortunately using the lite version is a requirement for my application of the visual as else the visual can not be exported to PDF from PowerBI online (using a power automate workflow)

**To Reproduce**

I can not share the full HTML due to the nature of the work but below is the JavaScript exactly as it appears within the HTML:

`<script>
        function sortTable() {
  var table, rows, switching, i, x, y, shouldSwitch;
  table = document.getElementById(""myTable"");
  switching = true;
  while (switching) {
    switching = false;
    rows = table.rows;
    for (i = 1; i < (rows.length - 1); i++) {
      shouldSwitch = false;
      x = parseInt(rows[i].getElementsByTagName(""td"")[7].innerHTML);
      y = parseInt(rows[i + 1].getElementsByTagName(""td"")[7].innerHTML);
      if (x > y) {
        shouldSwitch = true;
        break;
      }
    }
    if (shouldSwitch) {
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;
    }
  }
}
   sortTable()  
</script>"`
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/169843631/c27dd1bb-c89b-4b8e-863a-5c308f509731)

**Expected behavior**

'myTable' should be sorted based on the 7 th column (if you start counting with 0).

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/169843631/07127109-b49e-4683-80b1-08f7249630da)

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop and Online
 - OS: Windows 10
 - Browser: Chrome

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Lite Version: 1.4.1.0
 - Non-Lite Version: 1.4.1.0

Thank you very much for the support and I look forward to hearing from you!

- Simon

**Comment by Simon-Sieber1** [comment]
Dear community, 

Kindly following up here to see if anyone has thoughts on the issue outlined above. 

Best,
Simon

**Comment by dm-p** [comment]
Apologies for the delay in responding - I maintain these visuals for free and in my free time, so I'm not able to get to issues as they arise.

Javascript is not supported in HTML Content (lite). [Certified visuals are not permitted to dynamically execute Javascript supplied via user content](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified#certification-requirements:~:text=Arbitrary%20or%20dynamic%20code%20such%20as%20eval()%2C%20unsafe%20use%20of%20settimeout()%2C%20requestAnimationFrame()%2C%20setinterval(user%20input%20function)%2C%20and%20user%20input%20or%20user%20data.). The only way to satisfy this as you're attempting would be with the regular HTML Content visual.

Therefore if you need a visual with specific logic and need it to confirm to certification requirements, you would need to create your own custom visual, submit it to AppSource and request it be certified.

**Comment by Simon-Sieber1** [comment]
Not a worry! Thanks for confirming, I had understood that the (lite) version supported JavaScript that didn't reference external content hence the confusion. 

Again, thank you so much for the hard work and support on this visual!

**Comment by dm-p** [comment]
No worries—in retrospect, the site may be a bit confusing. The doc was always geared towards regular HTML Content (lite came along after years of being asked to make a certified version). [The Editions page](https://www.html-content.com/editions#lite-certified) was added to help clarify what's possible with the certified version and list which tags are supported and comply with certification requirements.

The site is due an overhaul, and I'll take this into account when I'm able to spend some time eon it so that we can better guide users as to what they can and can't do with it. I really appreciate the feedback.
