### ISSUE TITLE
[BUG] Iframe content renders but cannot login 

### ISSUE THREAD

**Issue by MDENDAN** [dm-p/powerbi-visuals-html-content#111]
I wanted to create card that with content as Iframe and I want to embed HubSpot data. The API works fine, and Login screen is rendering. The problem I am facing is I cannot login. It works on normal html editors but not inside HTML content visual inside power BI. Clicking Login button does not perform any action.

**To Reproduce**

**Comment by dm-p** [comment]
Hi - for security reasons Power BI custom visuals do not allow redirects or session state within iframes, so it is not possible to host a web application in here. This would be the same for all custom visuals, not just HTML Content.
