### ISSUE TITLE
[ENHANCEMENT] HTML Content Verification

### ISSUE THREAD

**Issue by CraigCopleyMRCC** [dm-p/powerbi-visuals-html-content#112]
Just wondering if it is possible to get the HTML Content verified like you have done with the lite version.

I was needing to use iframes and the unverified version looks like it would have worked but is blocked by admin as it is unverified, and the lite version does not support iframe.

**Comment by dm-p** [comment]
Hi there - It is not possible to certify HTML Content as it works currently. HTML Content (lite) is the solution to this problem and is permissive as a certified visual can get for this use case and is exactly the same as HTML Content, except for the functionality that MS does not permit in a certified visual. 

An iframe is counted as external content and therefore cannot be used in a certified visual. If you want iframe functionality then you have to use HTML Content. 

If your org allows it, they can add it as an [organizational visual](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-organization). If they have concerns this repo contains the source code they can insect and review independently.
