### ISSUE TITLE
[ENHANCEMENT] Please help me to advise to add feature of converting jira format to html

### ISSUE THREAD

**Issue by Deokjung-Kwon** [dm-p/powerbi-visuals-html-content#15]
Hello.

I think this project is perfect solution viewing HTML on Power BI.

However, I want to add a feature of converting JIRA markdown to html . 
I found npm project for this. (https://www.npmjs.com/package/jira2md)

But, I don't know where is original data for html.
below is my wrong code. Would you please how can i modify data?

`public update(options: VisualUpdateOptions) {
              // add to covert jira to html
                let dataView: DataView = options.dataViews[0];                
                this.textValue.text(j2m.jira_to_html(<string>dataView.single.value));`

**Comment by dm-p** [comment]
Hi there,

It's not clear from your question as to whether you're writing your own visual or looking to adapt this one, so I'll try and cover both bases.

This visual uses the [`table` `dataViewMapping`](https://github.com/dm-p/powerbi-visuals-html-content/blob/master/capabilities.json#L102) so if you are trying to use `single` when accessing the visual's `dataView`, then you will not find any data in the snippet of code you've provided. `single` only provides one data point for the `dataView`, and as this visual needs more than that, it is not a suitable implementation unless you can guarantee that you'll only ever need a single datum.

Please refer to the official documentation on [data view mappings](https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings#table-data-mapping?WT.mc_id=DP-MVP-5003712) for more detail with this, or if you can look in [`mapDataView()`](https://github.com/dm-p/powerbi-visuals-html-content/blob/master/src/ViewModel.ts#L78) to see how it's extracted within this visual if you're looking to adapt it.

If you're developing your own visual to do this, then it's better to ask these kinds of questions over at the [Power BI Community](https://community.powerbi.com/t5/Developer/bd-p/Developer). Be sure to provide your capabilities.json as well as any specific snippets of code, as this will ensure you get help more quickly.

Regards,

Daniel

**Comment by Deokjung-Kwon** [comment]
> Hi there,
> 
> It's not clear from your question as to whether you're writing your own visual or looking to adapt this one, so I'll try and cover both bases.
> 
> This visual uses the [`table` `dataViewMapping`](https://github.com/dm-p/powerbi-visuals-html-content/blob/master/capabilities.json#L102) so if you are trying to use `single` when accessing the visual's `dataView`, then you will not find any data in the snippet of code you've provided. `single` only provides one data point for the `dataView`, and as this visual needs more than that, it is not a suitable implementation unless you can guarantee that you'll only ever need a single datum.
> 
> Please refer to the official documentation on [data view mappings](https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings#table-data-mapping?WT.mc_id=DP-MVP-5003712) for more detail with this, or if you can look in [`mapDataView()`](https://github.com/dm-p/powerbi-visuals-html-content/blob/master/src/ViewModel.ts#L78) to see how it's extracted within this visual if you're looking to adapt it.
> 
> If you're developing your own visual to do this, then it's better to ask these kinds of questions over at the [Power BI Community](https://community.powerbi.com/t5/Developer/bd-p/Developer). Be sure to provide your capabilities.json as well as any specific snippets of code, as this will ensure you get help more quickly.
> 
> Regards,
> 
> Daniel

Thank you for kindly answer :) I resolve my question.
Kwon.
