### ISSUE TITLE
mailto hyperlink

### ISSUE THREAD

**Issue by Dennis-G95** [dm-p/powerbi-visuals-html-content#16]
**Describe the bug**

Dear,

When using mailto or tel we get this message:
![image](https://user-images.githubusercontent.com/74192219/98548717-1fdfca00-229a-11eb-8013-83a6d87dee84.png)

We are able to make normal 'https://www.' links work, but when using 'mailto' or 'tel' we get the above message in PowerBi Desktop and in the service nothing happens when we click on it.

Can you help us find what causes this error?
Thanks you in advance.

Kind regards,
Dennis

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop andPower BI Service
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1.0.2.0

**Additional context**
this is how the data looks:

This is the HTML we use:

HTML = <strong>"" &MarketingContacts[Title ]&"</strong><br>
<table style=""border-left-color: grey;"">
<body>
<tr>
<td>
<p><img src=""" & MarketingContacts[Link] & """ alt=""Image"" width=""50"" height=""66"" /></p>
</td>
<td>
<span style=""color: #0099cc;""><strong>"&MarketingContacts[Name]&"</strong></span><br>
<a href=tel:"&MarketingContacts[Phone]&">"&MarketingContacts[Phone]&"</a><br>
<a href='"&MarketingContacts[MailTo]&"'>"&MarketingContacts[Email]&"</a><br>
</td>
</tr>
</body>
</table><br>"

**Comment by dm-p** [comment]
Hi @Dennis-G95, and thanks for reaching out.

Despite `mailto:` working in core visuals, unfortunately [only the HTTP protocol is supported for custom visuals by Microsoft](https://docs.microsoft.com/en-us/power-bi/developer/visuals/launch-url?WT.mc_id=DP-MVP-5003712#restrictions). I'm working on a new set of documentation for the visual so will be sure to include this limitation in the details.

**Comment by Dennis-G95** [comment]
Dear dm-p,

Thank you for the clarification.
