### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MikeCarlo** [dm-p/powerbi-visuals-html-content#17]
**Describe the bug**

Reading through the documentation, one phrase was confusing

**To Reproduce**

Visit https://delightful-sea-0ba98881e.azurestaticapps.net/faq

The line _Using innerHTML, or D3.HTML (user data or user input)_
did not make sense to me. 

**Expected behavior**

I think what you are trying to say here is that using external code and pulling that in is acceptable. 
so examples would be something like using innerHTML or D3.html are approved external sources.

I would like to see a quick example of how I would pull that in, potentially

**Comment by dm-p** [comment]
The text is a direct lift from the visuals developer documentation to confirm that what the visual is doing (setting HTML dynamically) is not permitted as part of certification requirements - I'll refine this so it reads better.

**Comment by dm-p** [comment]
Hey @MikeCarlo - I've [updated the explanation a bit](https://delightful-sea-0ba98881e.azurestaticapps.net/faq#will-the-visual-be-certified) and hopefully this demystifies the MS wording. Let me know if still not clear, or if you have a better suggestion.

The site has also been refreshed with a little bit more content, notably:

* Updated *FAQ*
* Revised *CORS & Other Known Limitations* to provide more explanations of limitations
* Added *Videos* page w/first webinar
* Buy Me a Coffee Integration
