### ISSUE TITLE
Add Map Iframe by HTML to power bi 

### ISSUE THREAD

**Issue by Brachalevin** [dm-p/powerbi-visuals-html-content#21]
Hi,
I need to add to power bi Govmap iframe element with HTML
This is my iframe :
HTML = "<iframe id='ifrMap' frameborder= '0' scrolling= 'no' marginheight= '0' marginwidth= '0' width='350px' height='350px'src= 'https://www.govmap.gov.il/map.html?bb=1&zb=1&in=1&c=204000,595000&z=0' > </iframe>"
I have X,Y for every row in my data.
Do html-content  know iframe?
if yes, how can i do that?
thanks,
bracha.

**Comment by dm-p** [comment]
Hi there, and thanks for your question. `<iframe>` elements don't always work, but this is a limitation of custom visuals in Power BI. I have created #22 to explain this in a bit more detail and hopefully this clarifies things for you.

The short answer is: Desktop explicitly blocks `<iframe>` elements in any custom visual, so you need to test in the Service. It *might* work in the Service, depending on what the remote site allows.

Your case is one of the fortunate ones - when I publish to the Power BI Service, it will display:

![image](https://user-images.githubusercontent.com/10572054/100787949-451abf00-3479-11eb-8ffc-9f719f5ca712.png)

This is not a guarantee that it will always work - govmap.il may choose to revoke the permission for `origin`-less `<iframe>` elements at any time (which is how custom visuals are rendered in Power BI).

**Comment by Brachalevin** [comment]
Thank you very much for the answer !!
I have a follow-up question,
In My data I have X, Y and I want them to be displayed on the gov_map and
filter the map according to the whole report. is it possible?
This is the code I put and does not work:
HTMLX = "<iframe id = 'ifrMap' frameborder = '0' scrolling = 'no'
marginheight = '0' marginwidth = '0' width = '350px' height = '350px'src ='
https: //www.govmap .gov.il / map.html? bb = 1 & zb = 1 & in = 1 & c = "&
my_data [X] &", "& my_data [Y] &" & z = 0 '> </iframe> "
thanks.
bracha.


‫בתאריך יום ג׳, 1 בדצמ׳ 2020 ב-21:38 מאת ‪Daniel Marsh-Patrick‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dm-p** [comment]
Apologies for the delay - I'm currently on vacation and am not regularly looking at my personal projects. Unfortunately I don't know enough about your data model or use case to answer fully and would need more detail. One thing I would suggest is that `<iframe/>` tags should be self-closing, that is, don't write them like:

`<iframe id = 'ifrMap' ...> </iframe>`

but rather:

`<iframe id = 'ifrMap' ... />`

e.g. for the test I did in my above comment, the column expression was as follows:

```
<iframe id='ifrMap' frameborder= '0' scrolling= 'no' marginheight= '0' marginwidth= '0' width='350px' height='350px'src= 'https://www.govmap.gov.il/map.html?bb=1&zb=1&in=1&c=204000,595000&z=0' />
```

Regarding filtering, if your data going into the `<iframe/>`  URI should filter the map (depending on however govmap implement their embed) then it likely will. However as I don't support govmap, or have any knowledge of this service or your data model, then that would be something you'd need to check with them. If you wish for me to investigate then my services can be engaged professionally, but it's a little outside the scope of supporting this particular visual.

To round out the subject of filtering, this visual cannot filter other visuals, much like the built-in R or Python visuals can't either.

**Comment by Brachalevin** [comment]
thank you very match , you so help !!
something wrong and we  check it why.
  thank you !!
bracha.

‫בתאריך שבת, 5 בדצמ׳ 2020 ב-7:30 מאת ‪Daniel Marsh-Patrick‬‏ <‪
notifications@github.com‬‏>:‬
