### ISSUE TITLE
Use case to add tracking code

### ISSUE THREAD

**Issue by akukich2** [dm-p/powerbi-visuals-html-content#23]
Hi, my Marketing Director is requesting the following and I am wondering if this visual could be used:  He is running an ad on LinkedIn with a link to a Power Bi report (published with a public web code).  Wants to add LinkedIn tracking code to the report.

Let me know if you need any other information.   Thanks!

Ann Kukich
Channel Media Group
ann@channelmediagrp.com

**Comment by dm-p** [comment]
Hi @akukich2, and apologies for the delay in responding. I've been on leave and haven't been checking my personal projects during this time either.

I'm not a marketer, so I don't have any knowledge of how the LinkedIn tracking codes work (or access to them), unfortunately. Can you provide me with any examples of how these are implemented?

If the tracking link requires cookie access, then it will not work, as these are not permitted in custom visuals and blocked by the Power BI main window.

Another possibility might be to use something like the [Power BI Pixel](https://datachant.com/2020/01/06/power-bi-pixel-a-new-way-to-track-usage-on-power-bi/) implementation approach? This uses a combination of the data model and Power Automate to achieve something akin to tracking.
