### ISSUE TITLE
Support for <object> htmltag - [ENHANCEMENT]

### ISSUE THREAD

**Issue by geirdavidsen** [dm-p/powerbi-visuals-html-content#25]
I would like the visual to support viewing of different image formats and PDF related to a project involving invoice information

Support of the <object> tag would enable us to use the html content visual to show different image formats **AND**  PDF in the same visual through a measure which diverses on the _type_ attribute in the tag

ref: https://www.w3schools.com/tags/tag_object.asp

ex:
`<object>
  data="<<my blob url and key>>"
  type="application/pdf"
  width="100%"
  height="100%">
</object>`

Based on image format the measure could change the type to "image/tiff", "image/jpg" etc based on fileextenson from the blog entry.
ref: https://www.iana.org/assignments/media-types/media-types.xhtml#image

**Comment by dm-p** [comment]
Hi there, and thanks for your feature request.

The visual itself will attempt to parse any and all HTML tags but unfortunately the `<object>` tag is [not permitted by sandboxed iframes](https://www.w3schools.com/tags/att_iframe_sandbox.asp), which is how all custom visuals are hosted inside Power BI. 

High-level details of these sandboxing limitations are documented a bit further in #22, although I'll now extend the documentarion to include this particular limitation, as its not explicitly stated in there. There is nothing that I can do to enable this from my end, unless Microsoft choose to relax this particular restriction in the custom visual host.
