### ISSUE TITLE
[ENHANCEMENT] Message : No data available to display

### ISSUE THREAD

**Issue by noliverte** [dm-p/powerbi-visuals-html-content#26]
Hi,

I use your extension in Powerbi and it works great.

In my use case, I'm showing data in the html5 component, and it works fine. But when there is no data to display, I get a message that appears in the component "No data available to display." Is there a way to replace it with another message?

Thanks for your help

Noliverte

**Comment by dm-p** [comment]
Hi, and thanks for the feedback. The message is [configured in the visual's localised text](https://github.com/dm-p/powerbi-visuals-html-content/blob/1fd4e3bced15987628898c0d1b93c2d6e806798e/stringResources/en-US/resources.resjson#L27), but from an end-user standpoint, this is effectively "hard-coded" and not possible to change, unless you hack the .pbiviz.

I'll make a release available shortly with a feature that will work as follows - hopefully this will provide the most flexibility possible:

----

If there is no data to display, then the message will be displayed as normal by default, e.g.:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/10572054/103451005-53cbee80-4d23-11eb-845c-c5725efe59d7.png)

----

However, this message will be surfaced to the **Content Formatting** property menu as **"No Data" Message**, e.g.:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/10572054/103451032-9ab9e400-4d23-11eb-93f8-4e83d68cc157.png)

----

You can customise this like a regular property and this can replace the message, e.g.:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/10572054/103451050-e2407000-4d23-11eb-871d-7afb9759667f.png)

----

Or, you can write a measure containing HTML and use conditional formatting to display that instead, e.g.:

Measure DAX:
```<HTML> No Data Message = "<img src='https://icon-library.net/images/no-data-icon/no-data-icon-10.jpg' width='250'/>"```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/10572054/103451167-7eb74200-4d25-11eb-9f5f-79a432138199.png)

**Comment by dm-p** [comment]
This has been included in 1.1.0 of the visual, and has been submitted to AppSource. MS don't provide an ETA on when updates become available and the process can take anywhere from 2 weeks to 2 months. If you want to use the feature before then, you can obtain the standalone version of the visual from [its release page](https://github.com/dm-p/powerbi-visuals-html-content/releases/tag/1.1.0.15). 

Please note that this standalone version **does not auto-update** as it is no longer tied to the marketplace version, so if you are unsure what this means, then it's probably best to wait for it to become available.
