### ISSUE TITLE
Javascript output not displaying 

### ISSUE THREAD

**Issue by mastafaMicrosoft** [dm-p/powerbi-visuals-html-content#28]
Hi, 

Is it expected not to get d3.js scripts embedded in my html display in the custom visual on PowerBI? 

More precisely, I have an html file with a javascript which dynamically produces a scatter plot. I would like to visualize it on PowerBI. This works fine on any browser but I cannot make it work on PowerBI for some reason. The pure html part is correctly displayed on PowerBI but the interactive visual produced with d3.js does not work. 

**Any insight here?**

**Comment by dm-p** [comment]
Hi there - including a `<script>` tag that references an external JS file is not permitted by Power BI, unfortunately. 

Please find a list of currently known limitations [documented over at html-content.com](https://www.html-content.com/reference/limitations#what-doesnt-or-might-partially-work).

If you want to try and work with D3, without specifically coding a custom visual then perhaps you can try the [D3.js visual, also on AppSource](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381354?src=website&mktcmpid=overview&tab=Overview).
