### ISSUE TITLE
Selecting and copying text

### ISSUE THREAD

**Issue by jdagslet** [dm-p/powerbi-visuals-html-content#29]
Being able to select and copy text from the visual would be a great addition.

**Comment by arturogf** [comment]
Very much needed here as well. I am able to copy/paste when the html is an <iframe> referencing to another page (actually i am using daxformatter.com url in the iframe content). Might be helpful to understand from there, why I can... maybe related to something of the html generated by daxformatter.com?

Thanks for working on this.

**Comment by dm-p** [comment]
Thanks very much, folks for your feedback 🙂

I need to make some small maintenance updates to the visual, so as part of this, I'll add an 'Allow Text Select' in the **Content Formatting Menu** properties that can be enabled. If enabled, this will set the `user-select` style on the visual container to `text`.

MS explicitly sets this to `none` on the visual container, so I don't feel comfortable enabling it for all users, just in case it creates unintended side-effects for existing reports, but at least this way you can opt-in.

Note that we are also not able to tie any logic to the *Copy* behaviour of the context menu, as its content is managed by Power BI, so if you want to be able to copy/paste selected text then you will need to use Ctrl + C to do this.

Here's a quick demo of this in my dev environment:

![Text Select Prop](https://user-images.githubusercontent.com/10572054/119280758-d891b780-bc86-11eb-86d5-670394cb2d7c.gif)

This will also work for **Show Raw HTML**, if enabled..

I don't have an ETA on completion or release date at present, as I have a couple of other changes to make, and then the updated viz needs to go through AppSource submission, which can take some time. I'll try to keep you informed of progress on this issue.

**Comment by arturogf** [comment]
Thanks for this, looks good.

For now i have been able to inject some iframe code with <iframe srcdoc=" ... "> and it worked. Will be checking next updates!

Best

**Comment by dm-p** [comment]
Update has been submitted to AppSource. The approval process takes as long as it takes, unfortunately, so I don't have a date for when this will appear in all reports. As above, I'll update the issue when I get confirmation from the visuals team. To manage your expectations, this is likely to be 2-3 weeks, based on previous experiences but depends on how many other visuals are going through the process at the same time.

1.2.0 has some other changes, which I've [written up on the visual's website](https://www.html-content.com/change-log).

If you want to try the changes out in the meantime, there's a [standalone .pbiviz available in the repo's releases](https://github.com/dm-p/powerbi-visuals-html-content/releases/tag/1.2.0.16) that you can download and manually import. However, this is then independent from the version in AppSource and will not auto-update, so probably best you don't apply it to any production reports.

**Comment by dm-p** [comment]
The version containing these changes is now live in AppSource, so closing the issue.
