### ISSUE TITLE
Submitting a Power BI visual for certification

### ISSUE THREAD

**Issue by ThibaudLOREK** [dm-p/powerbi-visuals-html-content#31]
Hello,
I wish to see your visual with the certified Power BI visual badge. 
It makes me so sad to not be able to export my work in pdf.
Kiss from France

**Comment by dm-p** [comment]
Hi, and thanks for reaching out! 

I would also love to see the visual certified but it's [unfortunately not possible under the current rules](https://www.html-content.com/faq#will-the-visual-be-certified). I'd suggest trying the [Shielded HTML Viewer](https://appsource.microsoft.com/en-us/product/power-bi-visuals/wa200002144?tab=overview), which is certified, to see if this meets your needs.

**Comment by dm-p** [comment]
I was combing through previous issues and thought I could at least provide an update on this, in case anyone comes across it. [We now have HTML Content (lite)](https://appsource.microsoft.com/en-us/product/PowerBIVisuals/coacervolimited1596856650797.htmlcontent_certified), which is a certified version of HTML Content, but with more restrictive permissions on what you can render.
