### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jeckton** [dm-p/powerbi-visuals-html-content#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Workbook**

If applicable, attach screenshots or a sample workbook with data suitable for public viewing to help explain your problem.

**Power BI Setup (please complete the following information):**
 - Platform: [e.g. Power BI Desktop, Power BI Service]

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: [e.g. 2.0.0.0]

**Additional context**

**Comment by dm-p** [comment]
This appears to just contain the boilerplate template and no detail of an actual bug, so closing.
