### ISSUE TITLE
viewing YouTube videos

### ISSUE THREAD

**Issue by arnohoedelmans** [dm-p/powerbi-visuals-html-content#34]
Hi,

I know there is a way to play vimeo video's inside the power bi Service.
Is it possible to make YouTube video's play inside the visual as well?

If possible can you share the code?

Thanx

**Comment by dm-p** [comment]
Unfortunately YouTube videos aren't possible due to limitations on both the Power BI side and the YouTube side. This is all detailed in #22 but is also [documented here](https://www.html-content.com/reference/limitations) on the visual's website.

**Comment by arnohoedelmans** [comment]
Thanx for your quick reaction.
