### ISSUE TITLE
Power BI report with visual "HTML Content" does not show the content of an IFRAME inserted there. The IFRAME's sandbox attribute is set with the following flags: sandbox = "allow-same-origin allow-scripts".

### ISSUE THREAD

**Issue by ui-ro-ja** [dm-p/powerbi-visuals-html-content#49]
### **Description:**
Power BI report with visual "HTML Content" does not show the content of an IFRAME inserted there. 
The IFRAME's sandbox attribute is set with the following flags: sandbox = "allow-same-origin allow-scripts".

### **Details:**
If only the flag "allow-same-origin" is set you get the following error message from the Chrome inspector:
**Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.**

If both flags are set "allow-same-origin allow-scripts" you get the following error message:
****DOMException:** Failed to read the 'serviceWorker' property from 'Navigator': Service worker is disabled because the context is sandboxed and lacks the 'allow-same-origin' flag.**

It looks like the combination of the two flags doesn't work.

**Comment by dm-p** [comment]
Custom visuals are hosted in a sandboxed iframe with the `allow-scripts` permission. You can't add an iframe inside a custom visual with a less restrictive sandbox. Please refer to [this article on the website](https://www.html-content.com/reference/limitations#custom-visuals-high-level) for details on limitations.
