### ISSUE TITLE
Something go wrong while the html pages using <script>$.get/$.post</script>

### ISSUE THREAD

**Issue by codexq123** [dm-p/powerbi-visuals-html-content#56]
**Describe the bug**

Something go wrong while the html pages using <script>$.get/$.post</script>

**To Reproduce**

1. New a HTML content visuals in power bi
2. New a measure:
testEcharts = "<iframe src='http://127.0.0.1:8080/test.html' width:100%;height:100%></iframe>" 
Drop the measure to HTML content visuals.
3. Then we suppose the visuals should return the pages. But it did not show anything.

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop
 - OS: Windows10
 - Browser chrome, edge,ie

**My guess**

Something goes wrong with "$.post" in this HTML page, see below.

` <script>
svgPath = "http://127.0.0.1:8080/MySvg.svg";
$.post(svgPath, function (svg) {
   blablabla;
}
</script>`

Interestingly, while I change the svgPath to an external website, the problem can be solved. See below.

` <script>
svgPath = "https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/data/asset/geo/ksia-ext-plan-min.svg";
$.post(svgPath, function (svg) {
   blablabla;
}
</script>`

BTW, the page("http://127.0.0.1:8080/test.html") works well on chrome, edge, IE11, IE10 and IE9 EXCEPT IE8.

Could you help me? Thanks.

**Comment by dm-p** [comment]
Hi @codexq123, and thanks for your issue.

[HTML Content does not support scripting](https://www.html-content.com/reference/limitations#what-doesnt-or-might-partially-work). and I would recommend that if you did want to use scripting in Power BI, you probably create a dedicated custom visual for it as you'll be able to debug any coding issues much more easily.

The fact that you had this working is quite an achievement. I suspect that the reason that this works from a remote site is that you are now trying to access localhost (127.0.0.1) which is not permitted by sandboxed iframes. This is a limitation imposed by Microsoft and we have no ability to change this for custom visuals. You would need to continue to load from a CDN or another location without CORS restrictions. This challenge is also documented [on the page linked above](https://www.html-content.com/reference/limitations#custom-visuals-high-level) (a bit further down)/

**Comment by codexq123** [comment]
> Hi @codexq123, and thanks for your issue.
> 
> [HTML Content does not support scripting](https://www.html-content.com/reference/limitations#what-doesnt-or-might-partially-work), and I would recommend that if you did want to use scripting in Power BI, you probably create a dedicated custom visual for it as you'll be able to debug any coding issues much more easily.
> 
> The fact that you had this working is quite an achievement. I suspect that the reason that this works from a remote site is that you are now trying to access localhost (127.0.0.1) which is not permitted by sandboxed iframes. This is a limitation imposed by Microsoft and we have no ability to change this for custom visuals. You would need to continue to load from a CDN or another location without CORS restrictions. This challenge is also documented [on the page linked above](https://www.html-content.com/reference/limitations#custom-visuals-high-level) (a bit further down).

Thanks for the advice.  To solve this problem, I have tried a very stupid way. That is write an svg(xml) string in the HTML page and convert it to XML obj, instead of $.get(svgPath).
