### ISSUE TITLE
[BUG] Measure-Based Stylesheet field no longer accepts a table query field with new format pane enabled

### ISSUE THREAD

**Issue by bogesn** [dm-p/powerbi-visuals-html-content#58]
**Describe the bug**

Power BI's Feb 22 release has degraded the functionality for the Measure-Based Stylesheet field. With Power BI's new format pane preview enabled (on by default), the field is displayed, but it will not accept a field from a query table. Existing visuals retain the CSS styling set prior to the Power BI update, but the field now behaves as a textbox. New instances of the HTML visual will only accept CSS content pasted into the Measure-Based Stylesheet field.

After turning off the new format pane preview in Power BI's settings, the Measure-Based Stylesheet field is no longer displayed. However, it does display an Advanced Controls link that enables the user to select a query field containing CSS content.

To summarize, with the new format pane preview enabled, CSS can only be applied by pasting literal CSS text into the textbox displayed in the Measure-Based Stylesheet field. Any CSS updates must be copy-pasted into every HTML visual manually.

If the new format pane preview is turned off, the visual is again functional, but the experience different than before the Power BI update.

**To Reproduce**

Power BI version must be Feb 22 update.
1. Add a new HTML visual
2. Add the HTML content field
3. Attempt to add CSS content from a query table field.
4. Measure based stylesheet field will not accept a query table field. It will only accept literal CSS text pasted into the field.

**Expected behavior**

The Measure based stylesheet field should accept a query table field that contains CSS content.

**Screenshots/Workbook**

If applicable, attach screenshots or a sample workbook with data suitable for public viewing to help explain your problem.

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop
 - OS: Windows 11
 - Browser: Edge, but not applicable for desktop reason (I think).
 - Version: 1.2.0.16 (HTML visual version, if that's what is expected here).

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: 2.102.683.0 64-bit (February 2022)

**Additional context**

![image](https://user-images.githubusercontent.com/29830001/155277105-3a898ff9-7393-4826-814f-eb370a58dc2d.png)

**Comment by dm-p** [comment]
Hi, and thanks for reporting. I'm in the process of following-up with Microsoft about this one, as we're using their APIs for conditional formatting, and there are still a number of known issues here. I'd advise reverting to the old pane for now if you need this until I can get some direction on what I need to do (of if MS intend to fix it).

**Comment by bogesn** [comment]
Looks like the Power BI team is going to fix the issue.
https://community.powerbi.com/t5/Desktop/Share-your-thoughts-on-the-new-format-pane-preview/m-p/2404175#M862136

**Comment by dm-p** [comment]
I now have confirmation from the visuals team (which I have been fortunate to observe personally) that the May Desktop release will restore the conditional formatting for the new-style pane.
