### ISSUE TITLE
HTML tooltips only show the data on first hover [BUG]

### ISSUE THREAD

**Issue by Heraclys** [dm-p/powerbi-visuals-html-content#61]
In power bi service all the HTML tooltips only show the data on the first hover, after another hover it turns blank.
So for tooltips in power bi this visual is broken.

This started after the latest update of power bi service.
In power bi desktop everything still works.

**To Reproduce**

1. Create a Power BI dashboard with an object that has a tooltip that uses this HTML content visual.
2. Make sure the HTML code is generated from a DAX measure.
3. Publish the Power BI dashboard to Power BI web Service
4. Hover over the object to popup the tooltip.
5. You will notice that the visual will generate only on the first hover in Power BI Service.
6. If you refresh the web page it will work again but again only on a first hover.

**Screenshots/Workbook**
Here you can see the problem, where the visual is not loading anymore after a first hover:
![HTML_Tooltip_Not_Generating](https://user-images.githubusercontent.com/79487877/165740884-133cb18f-bc1e-4b44-8315-ac7076ce5ba5.jpg)

Here you can see what the visual should look like, this is in Power BI Desktop, here all still works:
![HTML_Tooltip_as_it_should_be](https://user-images.githubusercontent.com/79487877/165741020-efcfb6a7-cfe9-46a5-88d5-aea2a74c51a1.jpg)

**Power BI Setup:**
 - Platform: [Power BI Service]
 - OS: [Windows 10]
 - Browser [Chrome, Microsoft Edge]
 - Version [Service version13.0.18129.59]

**Additional context**

I created a PRO ticket at Power BI and they informed me on that this issue has to be resolved with the publisher of the visual and not with them.
Community posts about this issue:
[https://community.powerbi.com/t5/Issues/HTML-tooltips-only-show-the-data-on-first-hover/idi-p/2472994](https://community.powerbi.com/t5/Issues/HTML-tooltips-only-show-the-data-on-first-hover/idi-p/2472994)
[https://community.powerbi.com/t5/Service/Loading-HTML-content-on-report-page-tooltip-goes-to-blank-since/m-p/2472993](https://community.powerbi.com/t5/Service/Loading-HTML-content-on-report-page-tooltip-goes-to-blank-since/m-p/2472993)

**Comment by dm-p** [comment]
Hi, and thanks for raising your issue. I can indeed reproduce:

https://user-images.githubusercontent.com/10572054/165848140-83cb68ee-5be5-4228-82f2-5f9291268462.mp4

----

However, I can reproduce with any other custom visual too (here's Bullet Chart by OKViz):

https://user-images.githubusercontent.com/10572054/165848195-f1ee579b-6cef-4670-9cb7-53d8fe76f145.mp4

----

So, despite Microsoft Support asserting otherwise, they have broken tooltip behaviour in the Service somehow.

I will also add this feedback to the community post.
