### ISSUE TITLE
[ENHANCEMENT] Increase limit for HTML data content

### ISSUE THREAD

**Issue by mavnino** [dm-p/powerbi-visuals-html-content#62]
**Is your feature request related to a problem? Please describe.**

I have observed that if HTML data is bigger than 32kb then it is truncated

**Describe the solution you'd like**

Is it possible to increase or remove the limitation. 128kb should be enough for my purposes

**Comment by dm-p** [comment]
Hi there, and thanks bery much for your question.

We don't have control over the data that Power BI provides, and there are currently no restrictions in the visual on this. Depending on how you get your data into your model, you are typically capped at 32KB for a column. [Chris Webb has a great article on the subject here](https://blog.crossjoin.co.uk/2019/05/17/maximum-length-text-value-power-bi/), plus [this](https://blog.crossjoin.co.uk/2019/05/19/storing-large-images-in-power-bi-datasets/) and [this](https://blog.crossjoin.co.uk/2019/05/26/power-query-performance-and-expanding-columns/) as follow-ups.

If your situation differs to this scenario, can you please attach a workbook that reproduces the issue for you? I will take a look to see if there's anything else I can find out.
