### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jyngyconsulting** [dm-p/powerbi-visuals-html-content#68]
**Describe the bug**

Pseudo-elements do not work

**To Reproduce**

1. Go to CSS code
2. Add the block with ::before
3. run code
4. No result.

**Expected behavior**

Styling should change according to child content block
**Screenshots/Workbook**

If applicable, attach screenshots or a sample workbook with data suitable for public viewing to help explain your problem.

**Power BI Setup (please complete the following information):**
 - Platform: [e.g. Power BI Desktop, Power BI Service]

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: [e.g. 2.0.0.0]

**Additional context**

**Comment by dm-p** [comment]
Apologies for the delay in responding - I've been going through the issues list and have found a couple that have fallen through the cracks.

As far as I can tell, pseudo selectors are working as expected, e.g.:

Create a measure with a suitable selector and pseud selector, plus desired behavior:

```
<CSS> Pseudo Test = "
    img:hover {
        filter: grayscale(1);
    }
"
```

Add this to the visual's stylesheet and test:

https://github.com/dm-p/powerbi-visuals-html-content/assets/10572054/2989464b-16a1-47ab-bff0-5e1b00790378

If your case isn't working following a similar method, you can reopen with an example workbook reproducing your issue and I can investigate further.
