### ISSUE TITLE
[BUG] Text limit for HTML Text

### ISSUE THREAD

**Issue by SEBNYLEN** [dm-p/powerbi-visuals-html-content#87]
**Describe the bug**
I am visualizing formatted text on a Power BI Report and there is a text limit. You cannot scroll further, even though there is still text in the source field.

**To Reproduce**
1. Go to Power BI
3. Scroll down to last visable row of the formatted text field (my text field has 2 200 words)
4. See error as it is not possible to scroll down even further

**Expected behavior**
To have unlimited rows of text

**Screenshots/Workbook**
Not possible due to the sensitivity of the content

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop and Power BI Service
 - OS: Windows 10
 - Browser: Edge
 - Version: 114.0.1823.43 (Official build) (64-bit)

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: 2.118.621.0 64-bit (June 2023)

**Additional context**
None

**Comment by dm-p** [comment]
As you are unable to provide data to help reproduce the issue, please review #62 to determine if the column limits in Power BI are causing you the issue. 2,200 words could well be around 32K characters.

This can potentially be worked around using measures (which can have a limit of ~2M characters) as described in the linked blog posts in the comments in that issue.

**Comment by SEBNYLEN** [comment]
Thank you for the response, much appreciated!

Yes, I just found that out as well. So the limit of 32K characters seems to be the issue in my case 😢 

Will you be adding the work around using measures in a future version?

**Comment by dm-p** [comment]
Measures are supported already and there are [examples on the site](https://www.html-content.com/examples/dax-simple) as to how you can use them in conjunction with the visual - you may need to add a suitable column to the granularity role to create the necessary row context, but this concept is again explained on the site. As to how to concatenate columns into measures, I would suggest reading the blog posts linked in the comment on issue #62 as this provides much more detailed resources than I could provide here.

**Comment by SEBNYLEN** [comment]
I did not see that, thank you for pin pointing me! 

Have a great week!
