### ISSUE TITLE
'Export to PDF' currently not supported

### ISSUE THREAD

**Issue by HnrkThmsn** [dm-p/powerbi-visuals-html-content#93]
The visual does not support exporting.

In a published report, "HTML content" visuals does not support export to PDF. It would be great if this feature is supported.

![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/40858977/5a9cf90b-88c2-48d5-adca-12183a99bc48)

**Comment by dm-p** [comment]
[HTML Content is uncertified](https://www.html-content.com/faq#will-the-visual-be-certified) and does not support exporting. You can use [HTML Content (lite)](https://appsource.microsoft.com/en-us/product/PowerBIVisuals/coacervolimited1596856650797.htmlcontent_certified), which has a reduced feature set, but fulfils certification requirements for Microsoft. [Note that another update is coming very soon](https://coacervo.co/html-content-lite-1-4), which will improve the available features in this version.

**Comment by HnrkThmsn** [comment]
Thanks for a swift response. Hope PBI would allow URLs at some point...
