### ISSUE TITLE
[BUG] Visual not redering on reload

### ISSUE THREAD

**Issue by Helphs** [dm-p/powerbi-visuals-html-content#96]
Hello, I have a page using CSS, HTML and JavaScript. When I create the measure and put it in the Value field it works normaly, but if I edit any part of the code, resize the visual, refresh the source or enable and disable the "Show raw HTML" option, none of the elements created by the JS get rendered even though they work on the try.
It's like if the visual does not run the JS again and resets the HTML body.

Here is the sample code (github is removing the head and html tags, but the important stuff is there):

`
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        img {
            width: 3rem;
        }

        .collapsed {
            background-color: rgb(221, 221, 221);
        }
        .collapsed+ul {
            display: none;
        }

        .tree {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .tree ul {
            padding-top: 20px;
            position: relative;
            list-style-type: none;

            transition: all 0.5s;
            -webkit-transition: all 0.5s;
            -moz-transition: all 0.5s;
        }

        .tree li {
            float: left;
            text-align: center;
            list-style-type: none;
            position: relative;
            padding: 20px 5px 0 5px;

            transition: all 0.5s;
            -webkit-transition: all 0.5s;
            -moz-transition: all 0.5s;
        }

        /*We will use ::before and ::after to draw the connectors*/

        .tree li::before,
        .tree li::after {
            content: '';
            position: absolute;
            top: 0;
            right: 50%;
            border-top: 1px solid #ccc;
            width: 50%;
            height: 20px;
        }

        .tree li::after {
            right: auto;
            left: 50%;
            border-left: 1px solid #ccc;
        }

        /*We need to remove left-right connectors from elements without 
    any siblings*/
        .tree li:only-child::after,
        .tree li:only-child::before {
            display: none;
        }

        /*Remove space from the top of single children*/
        .tree li:only-child {
            padding-top: 0;
        }

        /*Remove left connector from first child and 
    right connector from last child*/
        .tree li:first-child::before,
        .tree li:last-child::after {
            border: 0 none;
        }

        /*Adding back the vertical connector to the last nodes*/
        .tree li:last-child::before {
            border-right: 1px solid #ccc;
            border-radius: 0 5px 0 0;
            -webkit-border-radius: 0 5px 0 0;
            -moz-border-radius: 0 5px 0 0;
        }

        .tree li:first-child::after {
            border-radius: 5px 0 0 0;
            -webkit-border-radius: 5px 0 0 0;
            -moz-border-radius: 5px 0 0 0;
        }

        /*Time to add downward connectors from parents*/
        .tree ul ul::before {
            content: '';
            position: absolute;
            top: 0;
            left: 50%;
            border-left: 1px solid #ccc;
            width: 0;
            height: 20px;
        }

        .tree li a {
            border: 1px solid #ccc;
            padding: 5px 10px;
            text-decoration: none;
            color: #666;
            font-family: arial, verdana, tahoma;
            font-size: 11px;

            border-radius: 5px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;

            transition: all 0.5s;
            -webkit-transition: all 0.5s;
            -moz-transition: all 0.5s;

            max-width: 10rem;

            display: flex;
            flex-direction: column;
            align-items: center;
            width: fit-content;
            margin: auto;
        }

        /*Time for some hover effects*/
        /*We will apply the hover effect the the lineage of the element also*/
        .tree li a:hover,
        .tree li a:hover+ul li a {
            background: #c8e4f8;
            color: #000;
            border: 1px solid #94a0b4;
        }

        /*Connector styles on hover*/
        .tree li a:hover+ul li::after,
        .tree li a:hover+ul li::before,
        .tree li a:hover+ul::before,
        .tree li a:hover+ul ul::before {
            border-color: #94a0b4;
        }
    </style>
</head>

<body>

    <div class='tree'>
    </div>

    <script>

        // cada node é um quadradinho no flowchart
        const nodes = [
            {
                id: 1,
                name: 'Ferrosos',
                idParent: '',
                group: 'Regiçao',
                img: 'https://static.vecteezy.com/ti/vetor-gratis/p3/12721545-icone-de-meme-doge-gratis-vetor.jpg'
            },
            {
                id: 2,
                name: 'outro',
                idParent: 1,
                group: 'Corredor',
                img: 'https://static.vecteezy.com/ti/vetor-gratis/p3/12721545-icone-de-meme-doge-gratis-vetor.jpg'
            },
            {
                id: 10,
                name: 'Mais um dhasbhdbsdbjasdjhasdbsadsajdbsdbjas bdjhsbdjhasbdhsbdhsabdh asbhbsadas',
                idParent: '',
                group: 'Complexo',
                img: 'https://static.vecteezy.com/ti/vetor-gratis/p3/12721545-icone-de-meme-doge-gratis-vetor.jpg'
            },
            {
                id: 3,
                name: 'Mais um quem',
                idParent: 1,
                group: 'Complexo',
                img: 'https://static.vecteezy.com/ti/vetor-gratis/p3/12721545-icone-de-meme-doge-gratis-vetor.jpg'
            },
            {
                id: 3,
                name: 'Mais um quem',
                idParent: 10,
                group: 'Complexo',
                img: 'https://static.vecteezy.com/ti/vetor-gratis/p3/12721545-icone-de-meme-doge-gratis-vetor.jpg'
            },
            {
                id: 3,
                name: 'Mais um',
                idParent: 10,
                group: 'Complexo',
                img: 'https://static.vecteezy.com/ti/vetor-gratis/p3/12721545-icone-de-meme-doge-gratis-vetor.jpg'
            },
            {
                id: 3,
                name: 'Mais um',
                idParent: 1,
                group: 'Complexo',
                img: ''
            },
        ]

        console.log(JSON.stringify(nodes))

        // função de contrói um árvore de li's desde o elemento mais profundo até o mais alto
        function buildTree(member, members) {

            // procura todos os descendentes diretos de um node dentre todos os outros nodes
            const descendants = []
            for (let candidate of members) {
                if (member.id === candidate.idParent) {
                    descendants.push(candidate)
                }
            }

            // se não foi encontrado nenhum descendente, é criado o li desse node do fundo e retorna esse li
            if (descendants.length === 0) {
                const descElement = document.createElement('li')
                descElement.innerHTML = `
                <a href='#'>
                    <img src='${member.img ?? 'https://clipart-library.com/images/kcKozGdni.png'}'>
                    <span>${member.name}</span>
                </a>
                `
                return descElement
            }

            // se foram encontrados descendentes ele deve fazer outra chamada da buildTree para cada um deles para checar se o descendente tem mais descentes
            const childrenElements = []
            for (let desc of descendants) {
                // chamada recursiva que contrói a árvore de baixo para cima
                childrenElements.push(buildTree(desc, members))
            }

            // o parentElement é o elemento que possui descendentes, a única diferença em realação ao li simples que é criado mais para cima é um ul onde são colocados os descendentes
            const parentElement = document.createElement('li')
            const innerAnchor = document.createElement('a')
            innerAnchor.href = '#'
            innerAnchor.innerHTML = `
                <img src='${member.img ?? 'https://clipart-library.com/images/kcKozGdni.png'}'>
                <span>${member.name}</span>
            `

            innerAnchor.addEventListener('click', (e) => {
                e.preventDefault()
                console.log(innerAnchor.classList.toggle('collapsed'))  
            })

            parentElement.appendChild(innerAnchor)

            // o family element é simplesmente o ul do pai para guardar os filhos
            const familyElement = document.createElement('ul')
            for (let childElement of childrenElements) {
                familyElement.appendChild(childElement)
            }

            parentElement.appendChild(familyElement)

            return parentElement
        }

        // pegando os nodes de topo e o resto
        const topNodes = nodes.filter((e) => e.idParent === '')
        const childNodes = nodes.filter((e) => !topNodes.includes(e))

        // criando e inserindo as árvores na div base
        const base = document.querySelector('.tree')

        for (node of topNodes) {
            const newTree = document.createElement('ul')
            newTree.appendChild(buildTree(node, childNodes))
            base.appendChild(newTree)
        }

    </script>

</body>

</html>`

1 - Create a measure with the code above as a string;
2 - Put the measure in the in the Values field of the visual;
3 - refresh the source, resize the visual or anything of the sort

I expect the visual to maintain the HTML state it had after the first JS run or run the JS again after doing any of the things that break the visual. 

**Power BI Setup (please complete the following information):**
 - Platform: Power BI Desktop 
 - OS: Windows 10
 - Browser: Chrome
 - Version: 2.121.644.0 64-bit

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: 1.4.0.0

**Comment by dm-p** [comment]
Situations like this are one of the many reasons we can't reliably support JS in the visual (And why we officially don't). I have expanded on some of the challenges of this in #28 and #56. [You can also refer to this comment](https://github.com/dm-p/powerbi-visuals-html-content/issues/79#issuecomment-1424851788) for more details on how the DOM is updated by Power BI any time something happens on the canvas or outside the visual. Essentially, we can't stop things from being re-rendered, so you can't really maintain state across updates.

If you're trying to build something with JS, it's really a use case for building a proper custom visual, as you can define your own logic and statefulness within your visual's JS that is easier to manage than in a generic visual such as this one.

**Comment by Helphs** [comment]
Hi, thank you for the clarification, as you suggested I ended up doing my on visual.

**Comment by dm-p** [comment]
Glad to hear you got your own visual working! I'll close this now that you have a resolution.
