### ISSUE TITLE
[BUG] The link is malformed: #Top

### ISSUE THREAD

**Issue by rudzimj** [dm-p/powerbi-visuals-html-content#99]
**Describe the bug**
I don't see this called out in the documentation, so want to check. Should we be able to create anchor tags within the visual and link to them? We are getting an error message: `The link is malformed: #Top`

**To Reproduce**

1. Create a new measure:
```
HTML = "<html>
<body>
<h1><a name=""Top"">Summary</a></h1>
<b>Sample HTML Report</b>
<ul><li><a href=""#Queries"">143 Queries</a></li>
<li><a href=""#Tables"">145 Tables</a></li>
<li><a href=""#Reports"">0 Reports</a></li>
<li><a href=""#Forms"">0 Forms</a></li>
<li><a href=""#Macros"">2 Macro modules</a></br></li></ul>

<a name=""Queries""><h2>Queries</a>
<a href=""#Top"">Back to top</a></h2>

<a name=""Tables""><h2>Tables</a>
<a href=""#Top"">Back to top</a></h2>

<a name=""Reports""><h2>Reports</a>
<a href=""#Top"">Back to top</a></h2>
    
<a name=""Forms""><h2>Forms</a>
<a href=""#Top"">Back to top</a></h2>

<a name=""Macros""><h2>Macros</a>    
<a href=""#Top"">Back to top</a></br>
</body>
</html>
"
```
2. Add HTML Content visual with measure
3. Turn on option **Allow opening URLs**
4. Click on any link to see error

**Expected behavior**

The visual should scroll to the anchor tag.

**Screenshots/Workbook**

<img width="504" alt="image" src="https://github.com/dm-p/powerbi-visuals-html-content/assets/36211641/7e58af1e-42ec-4def-a683-913ae45c4c3d">

**Power BI Setup:**
 - Platform: Power BI Desktop
 - OS: Windows 10
 - Version: 2.122.746.0 64-bit (October 2023)

**Visual Information:**
 - Version: Power BI Visual 1.4.1.0

**Additional context**

After publishing to the Power BI service, when you hover over the link, you can see the malformed URL:
![image](https://github.com/dm-p/powerbi-visuals-html-content/assets/36211641/a2cfeb81-bf45-4b9a-883b-19f420c3d5d9)

If `#top` was placed before the query string (`?locale=en-US&emCVBundle=1&pbiglobals=1`), I think this might work. Is that controllable by the visual, or is that handled by Power BI and beyond our control?

**Comment by dm-p** [comment]
Hi, and thanks for raising.

[It is stated in the documentation](https://www.html-content.com/reference/properties#allow-opening-urls) that only URLs with the `http` or `https` protocols are permitted. Anchor links will not work, unfortunately, as [MS imposes this restriction on all custom visuals](https://learn.microsoft.com/en-us/power-bi/developer/visuals/launch-url#restrictions).

The only way to circumvent this would be to put your content in its own iframe (but that would involve loading it from somewhere else).

**Comment by rudzimj** [comment]
Thanks
